version: "3.8"

services:
  ghost:
    image: ghost:latest
    ports:
      - "2368:2368"
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ghost
      database__connection__password: root
    depends_on:
      - mysql
    volumes:
      - ./mysql_data:/var/lib/mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql
